language: node_js
node_js:
- 11.10.1
dist: bionic
addons:
  ssh_known_hosts:
  - 165.22.115.151
before_install:
- openssl aes-256-cbc -K $encrypted_543afad2e0cd_key -iv $encrypted_543afad2e0cd_iv
  -in scripts/gatsby-deploy.enc -out scripts/gatsby-deploy -d
- eval "$(ssh-agent -s)"
- cp scripts/gatsby-deploy ~/.ssh/gatsby-deploy
- chmod 600 ~/.ssh/gatsby-deploy
- ssh-add ~/.ssh/gatsby-deploy
- echo -e "Host 165.22.115.151\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
- provider: script
  skip_cleanup: true
  script: bash scripts/deploy.sh
  on:
    branch: master
git:
  depth: 9999999